### ISSUE TITLE
expired domains

### ISSUE THREAD

**Issue by MohcineDev** [DevC-Casa/awesome-morocco#115]
expired domain names or connectivity issues
### Podcasts
- Business B nab
- DevCast

### Developers 
- Meriem Zaid

**Comment by ihssanehatim** [comment]
Thank you @MohcineDev for reporting the issue, I've updated `Ihssane Hatim`'s domain (mine) .

**Comment by aboullaite** [comment]
@JefferyHus can you update the domain name for pentium or remove it ?

**Comment by JefferyHus** [comment]
The domain should be working tomorrow. Thanks for the note !!

**Comment by JefferyHus** [comment]
@iMeriem & @LaasriNadia can you please check your dead links?

**Comment by MohcineDev** [comment]
updates

**Comment by LaasriNadia** [comment]
Fixed.
