### ISSUE TITLE
adding youtube channel

### ISSUE THREAD

**Issue by Mouradouchane** [DevC-Casa/awesome-morocco#123]
hi , i want to put my youtube channel here in list , "can i" & thanks in advanced !

**Comment by JefferyHus** [comment]
Open a PR or share your youtube channel here 😄

**Comment by Mouradouchane** [comment]
@JefferyHus , thanks man , this is my channel 😃 .
https://www.youtube.com/c/undefinedprogramming/videos

**Comment by JefferyHus** [comment]
Good content 👍
